### ISSUE TITLE
Is this API header key example fiction? 

### ISSUE THREAD

**Issue by piejanssens** [SAP-samples/teched2021-developer-keynote#15]
https://github.com/SAP-samples/teched2021-developer-keynote/blob/main/section/cap/srv/cat-service.js#L23

I'd expect OAuth 2.0 SAML bearer assertion is used to authenticate with the SF OData API, but I cannot see any traces of this in the sample. For this you'd need to include the `sap-successfactors-extensibility` service in the project and I would like to see what is needed for CAP to propagate the `req.user.id` to the external service using OAuth 2.0 SAML bearer assertion.

Could the sample be updated so that it's designed to work with the production destination 'sfsfDest' (in the cds.env) in the first place?

**Comment by jung-thomas** [comment]
Well if you were running in production you would bind to a destination named sfsfDest which would be an SAP BTP Destination
https://github.com/SAP-samples/teched2021-developer-keynote/blob/main/section/cap/package.json#L63
https://cap.cloud.sap/docs/guides/consuming-services#btp-destinations

Or if you were using Kyma as you suggested with the sap-successfactors-extensibility service this would be name of the extensibility service instance. https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/f371f81d06c64a0fb507307c9ad24646.html

**Comment by jung-thomas** [comment]
I would add that the API Key portion of the example is necessary if you want to test with the API Hub Sandbox; which many people that might not have access to a SuccessFactors instance might want to do.

**Comment by piejanssens** [comment]
Thanks @jung-thomas. I now played around a little with the external service and got it working. I think I was just thrown off a little too much seeing that API header in the service implementation 😛
