### ISSUE TITLE
Issue when trying to access an external odata service(with creentials)

### ISSUE THREAD

**Issue by ahmedkhan29789** [SAP-samples/teched2021-developer-keynote#16]
Hi Thomas,

I was trying the same way to access one external odata service which have credentials as well, while trying to access the json data afetr running "CDS WATCH", I am getting this error, I am not able to understand what i have done wrong, Can you please help by looking at this error what is going wrong

user: sap-ibp-promotions $ **cds watch**
 
cds serve all --with-mocks --in-memory? 
watching: cds,csn,csv,ts,mjs,cjs,js,json,properties,edmx,xml,env,css,gif,html,jpg,png,svg... 
live reload enabled for browsers 
        _______________________
 
[cds] - model loaded from 2 file(s):

  ./srv/catalog-service.cds
  ./srv/external/SapIbp.csn

[cds] - connect using bindings from: { registry: '~/.cds-services.json' }
[cds] - connect to db > sqlite { database: ':memory:' }
[cds] - connect to SapIbp > odata-v2 {
  url: 'https://my3011-api.scmibp1.ondemand.com/sap/opu/odata/IBP/PLANNING_DATA_API_SRV',
  authentication: '...',
  username: 'BTPUSER',
  password: '...'
}
[cds] - serving CatalogService { at: '/catalog', impl: './srv/catalog-service.js' }

[cds] - server listening on { url: 'http://localhost:4004' }
[cds] - launched at 12/26/2021, 10:10:55 PM, in: 550.699ms
[cds] - [ terminate with ^C ]

[cds] - GET /catalog/BTPPROMO
[remote] - Error: Error during request to remote service: Request failed with status code 400
    at createError (/home/user/projects/sap-ibp-promotions/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/user/projects/sap-ibp-promotions/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/user/projects/sap-ibp-promotions/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  config: {
    url: "/commit?P_TransactionID='undefined'",
    method: 'get',
    proxy: false,
    baseURL: 'https://my3011-api.scmibp1.ondemand.com/sap/opu/odata/IBP/PLANNING_DATA_API_SRV',
    timeout: 60000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    data: undefined
  },
  request: {
    method: 'GET',
    url: "https://my3011-api.scmibp1.ondemand.com/sap/opu/odata/IBP/PLANNING_DATA_API_SRV/commit?P_TransactionID='undefined'",
    headers: {
      Accept: 'application/json,text/plain',
      authorization: 'Basic ...',
      'accept-language': 'en',
      'User-Agent': 'axios/0.21.4'
    }
  },
  response: {
    status: 400,
    statusText: 'Bad Request',
    headers: {
      'set-cookie': [
        'sap-usercontext=sap-client=100; path=/',
        'SAP_SESSIONID_BBT_100=ud8ssJ49wDcgirRIiclHfbgZ13lmmBHsrYv6Fj4KKec%3d; path=/; secure; HttpOnly'
      ],
      'content-type': 'application/json;charset=utf-8',
      'content-length': '1067',
      dataserviceversion: '1.0',
      'sap-server': 'true',
      'sap-perf-fesrec': '140349.000000',
      'x-content-type-options': 'nosniff',
      'strict-transport-security': 'max-age=31536000; includeSubDomains',
      'x-xss-protection': '1; mode=block'
    },
    body: {
      error: {
        code: '/IBP/EXTRACT_MSG/064',
        message: {
          lang: 'en',
          value: 'Transaction ID undefined does not exist.'
        },
        innererror: {
          application: {
            component_id: 'SCM-IBP-INT-ODT',
            service_namespace: '/IBP/',
            service_id: 'PLANNING_DATA_API_SRV',
            service_version: '0001'
          },
          transactionid: '3372965542570250E0061C8E835D6D26',
          timestamp: '20211226221105.2749840',
          Error_Resolution: {
            SAP_Transaction: 'For backend administrators: use ADT feed reader "SAP Gateway Error Log" or run transaction /IWFND/ERROR_LOG on SAP Gateway hub system and search for entries with the timestamp above for more details',
            SAP_Note: 'See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)'
          },
          errordetails: [
            {
              ContentID: '',
              code: '/IBP/CX_PLNG_DATA_DI_API',
              message: 'Transaction ID undefined does not exist.',
              propertyref: '',
              severity: 'error',
              transition: false,
              target: ''
            },
            {
              ContentID: '',
              code: '/IWBEP/CX_MGW_BUSI_EXCEPTION',
              message: 'Transaction ID BATCH_ID does not exist.',
              propertyref: '',
              severity: 'error',
              transition: false,
              target: ''
            }
          ]
        }
      }
    }
  },
  isAxiosError: true,
  correlationId: 'c229a4d8-319e-467f-a904-3d923dc0264b'
}
[cds] - Error: Error during request to remote service: Request failed with status code 400
    at run (/home/user/projects/sap-ibp-promotions/node_modules/@sap/cds/libx/_runtime/remote/utils/client.js:248:25)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async RemoteService.<anonymous> (/home/user/projects/sap-ibp-promotions/node_modules/@sap/cds/libx/_runtime/remote/Service.js:179:20)
    at async next (/home/user/projects/sap-ibp-promotions/node_modules/@sap/cds/lib/serve/Service-dispatch.js:74:17)
    at async RemoteService.handle (/home/user/projects/sap-ibp-promotions/node_modules/@sap/cds/lib/serve/Service-dispatch.js:72:10)
    at async next (/home/user/projects/sap-ibp-promotions/node_modules/@sap/cds/lib/serve/Service-dispatch.js:74:17)
    at async RemoteService.handle (/home/user/projects/sap-ibp-promotions/node_modules/@sap/cds/lib/serve/Service-dispatch.js:72:10)
    at async RemoteService.commit (/home/user/projects/sap-ibp-promotions/node_modules/@sap/cds/lib/serve/Transaction.js:66:34)
    at async ODataRequest.emit (/home/user/projects/sap-ibp-promotions/node_modules/@sap/cds/lib/req/context.js:55:9)
    at async ApplicationService.commit (/home/user/projects/sap-ibp-promotions/node_modules/@sap/cds/lib/serve/Transaction.js:113:7) {
  statusCode: 502,
  innererror: Error: Error during request to remote service: Request failed with status code 400
      at createError (/home/user/projects/sap-ibp-promotions/node_modules/axios/lib/core/createError.js:16:15)
      at settle (/home/user/projects/sap-ibp-promotions/node_modules/axios/lib/core/settle.js:17:12)
      at IncomingMessage.handleStreamEnd (/home/user/projects/sap-ibp-promotions/node_modules/axios/lib/adapters/http.js:269:11)
      at IncomingMessage.emit (events.js:412:35)
      at endReadableNT (internal/streams/readable.js:1317:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21) {
    config: {
      url: "/commit?P_TransactionID='undefined'",
      method: 'get',
      proxy: false,
      baseURL: 'https://my3011-api.scmibp1.ondemand.com/sap/opu/odata/IBP/PLANNING_DATA_API_SRV',
      timeout: 60000,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      data: undefined
    },
    request: {
      method: 'GET',
      url: "https://my3011-api.scmibp1.ondemand.com/sap/opu/odata/IBP/PLANNING_DATA_API_SRV/commit?P_TransactionID='undefined'",
      headers: {
        Accept: 'application/json,text/plain',
        authorization: 'Basic ...',
        'accept-language': 'en',
        'User-Agent': 'axios/0.21.4'
      }
    },
    response: {
      status: 400,
      statusText: 'Bad Request',
      headers: {
        'set-cookie': [
          'sap-usercontext=sap-client=100; path=/',
          'SAP_SESSIONID_BBT_100=ud8ssJ49wDcgirRIiclHfbgZ13lmmBHsrYv6Fj4KKec%3d; path=/; secure; HttpOnly'
        ],
        'content-type': 'application/json;charset=utf-8',
        'content-length': '1067',
        dataserviceversion: '1.0',
        'sap-server': 'true',
        'sap-perf-fesrec': '140349.000000',
        'x-content-type-options': 'nosniff',
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        'x-xss-protection': '1; mode=block'
      },
      body: {
        error: {
          code: '/IBP/EXTRACT_MSG/064',
          message: {
            lang: 'en',
            value: 'Transaction ID undefined does not exist.'
          },
          innererror: {
            application: {
              component_id: 'SCM-IBP-INT-ODT',
              service_namespace: '/IBP/',
              service_id: 'PLANNING_DATA_API_SRV',
              service_version: '0001'
            },
            transactionid: '3372965542570250E0061C8E835D6D26',
            timestamp: '20211226221105.2749840',
            Error_Resolution: {
              SAP_Transaction: 'For backend administrators: use ADT feed reader "SAP Gateway Error Log" or run transaction /IWFND/ERROR_LOG on SAP Gateway hub system and search for entries with the timestamp above for more details',
              SAP_Note: 'See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)'
            },
            errordetails: [
              {
                ContentID: '',
                code: '/IBP/CX_PLNG_DATA_DI_API',
                message: 'Transaction ID undefined does not exist.',
                propertyref: '',
                severity: 'error',
                transition: false,
                target: ''
              },
              {
                ContentID: '',
                code: '/IWBEP/CX_MGW_BUSI_EXCEPTION',
                message: 'Transaction ID BATCH_ID does not exist.',
                propertyref: '',
                severity: 'error',
                transition: false,
                target: ''
              }
            ]
          }
        }
      }
    },
    isAxiosError: true,
    correlationId: 'c229a4d8-319e-467f-a904-3d923dc0264b'
  },
  id: '1867977',
  level: 'ERROR',
  timestamp: 1640556665315
}

**Comment by ahmedkhan29789** [comment]
My package.json looks like this
![image](https://user-images.githubusercontent.com/22063881/147421281-dc9c8b89-9384-455e-a098-1c5dca04f6a0.png)

**Comment by jung-thomas** [comment]
As this is a different service and different application you are calling, perhaps here isn't the best place to ask your question.  Maybe better on the SAP Community Q&A or as a support ticket. It would seem however that you are missing a required field in the request:
**value: 'Transaction ID undefined does not exist.'**
